export {default as add} from './api/add';
export {default as concat} from './api/concat';
export {default as divide} from './api/divide';
export {default as exp} from './api/exp';
export {default as multiply} from './api/multiply';
export {default as ones} from './api/ones';
export {default as subtract} from './api/subtract';
export {default as transpose} from './api/transpose';
export {default as zeros} from './api/zeros';